import { Question, JLPTLevel } from './types'

// 题目数据（根据参考网站整理）
export const sampleQuestions: Record<JLPTLevel, Question[]> = {
  N5: [
    // 看汉字选择平假名
    {
      id: 'n5-1',
      level: 'N5',
      type: 'kanji-to-hiragana',
      question: '影響',
      options: ['えいきょう', 'えいが', 'えいご', 'えん'],
      correctAnswer: 0,
      explanation: '影響（えいきょう）意思是"影响"',
    },
    {
      id: 'n5-2',
      level: 'N5',
      type: 'kanji-to-hiragana',
      question: '明るい',
      options: ['あかるい', 'あおい', 'あかい', 'あつい'],
      correctAnswer: 0,
      explanation: '明るい（あかるい）意思是"明亮的"',
    },
    {
      id: 'n5-3',
      level: 'N5',
      type: 'kanji-to-hiragana',
      question: '新しい',
      options: ['あたらしい', 'あつい', 'あまい', 'あさい'],
      correctAnswer: 0,
      explanation: '新しい（あたらしい）意思是"新的"',
    },
    {
      id: 'n5-4',
      level: 'N5',
      type: 'kanji-to-hiragana',
      question: '高い',
      options: ['たかい', 'たのしい', 'たべる', 'たまご'],
      correctAnswer: 0,
      explanation: '高い（たかい）意思是"高的"',
    },
    {
      id: 'n5-5',
      level: 'N5',
      type: 'kanji-to-hiragana',
      question: '大きい',
      options: ['おおきい', 'おいしい', 'おかあさん', 'おかね'],
      correctAnswer: 0,
      explanation: '大きい（おおきい）意思是"大的"',
    },
    // 看假名选择汉字
    {
      id: 'n5-6',
      level: 'N5',
      type: 'hiragana-to-kanji',
      question: 'あおい',
      options: ['青い', '赤い', '白い', '黒い'],
      correctAnswer: 0,
      explanation: 'あおい（青い）意思是"蓝色的"',
    },
    {
      id: 'n5-7',
      level: 'N5',
      type: 'hiragana-to-kanji',
      question: 'あさ',
      options: ['朝', '足', '頭', '手'],
      correctAnswer: 0,
      explanation: 'あさ（朝）意思是"早晨"',
    },
    {
      id: 'n5-8',
      level: 'N5',
      type: 'hiragana-to-kanji',
      question: 'いえ',
      options: ['家', '池', '椅子', '医者'],
      correctAnswer: 0,
      explanation: 'いえ（家）意思是"家"',
    },
    {
      id: 'n5-9',
      level: 'N5',
      type: 'hiragana-to-kanji',
      question: 'きのう',
      options: ['昨日', '今日', '明日', '今年'],
      correctAnswer: 0,
      explanation: 'きのう（昨日）意思是"昨天"',
    },
    {
      id: 'n5-10',
      level: 'N5',
      type: 'hiragana-to-kanji',
      question: 'もんだい',
      options: ['問題', '門隊', '設題', '猛題'],
      correctAnswer: 0,
      explanation: 'もんだい（問題）意思是"问题"',
    },
    // 片假名翻译成中文
    {
      id: 'n5-11',
      level: 'N5',
      type: 'katakana-to-chinese',
      question: 'カメラ',
      options: ['照相机', '电脑', '电话', '电视'],
      correctAnswer: 0,
      explanation: 'カメラ（camera）意思是"照相机"',
    },
    {
      id: 'n5-12',
      level: 'N5',
      type: 'katakana-to-chinese',
      question: 'テレビ',
      options: ['电视', '电话', '桌子', '磁带'],
      correctAnswer: 0,
      explanation: 'テレビ（television）意思是"电视"',
    },
    {
      id: 'n5-13',
      level: 'N5',
      type: 'katakana-to-chinese',
      question: 'コーヒー',
      options: ['咖啡', '红茶', '绿茶', '果汁'],
      correctAnswer: 0,
      explanation: 'コーヒー（coffee）意思是"咖啡"',
    },
    {
      id: 'n5-14',
      level: 'N5',
      type: 'katakana-to-chinese',
      question: 'パン',
      options: ['面包', '米饭', '面条', '蛋糕'],
      correctAnswer: 0,
      explanation: 'パン（pan）意思是"面包"',
    },
    {
      id: 'n5-15',
      level: 'N5',
      type: 'katakana-to-chinese',
      question: 'ノート',
      options: ['笔记本', '铅笔', '橡皮', '书包'],
      correctAnswer: 0,
      explanation: 'ノート（note）意思是"笔记本"',
    },
  ],
  N4: [
    // 看汉字选择平假名
    {
      id: 'n4-1',
      level: 'N4',
      type: 'kanji-to-hiragana',
      question: '影響',
      options: ['えいきょう', 'えいが', 'えいご', 'えんりょ'],
      correctAnswer: 0,
      explanation: '影響（えいきょう）意思是"影响"',
    },
    {
      id: 'n4-2',
      level: 'N4',
      type: 'kanji-to-hiragana',
      question: '遠慮',
      options: ['えんりょ', 'えんりょう', 'えいきょう', 'えいが'],
      correctAnswer: 0,
      explanation: '遠慮（えんりょ）意思是"客气"',
    },
    {
      id: 'n4-3',
      level: 'N4',
      type: 'kanji-to-hiragana',
      question: '安心',
      options: ['あんしん', 'あんぜん', 'あんない', 'あいさつ'],
      correctAnswer: 0,
      explanation: '安心（あんしん）意思是"安心"',
    },
    {
      id: 'n4-4',
      level: 'N4',
      type: 'kanji-to-hiragana',
      question: '安全',
      options: ['あんぜん', 'あんしん', 'あんない', 'あいさつ'],
      correctAnswer: 0,
      explanation: '安全（あんぜん）意思是"安全"',
    },
    {
      id: 'n4-5',
      level: 'N4',
      type: 'kanji-to-hiragana',
      question: '案内',
      options: ['あんない', 'あんしん', 'あんぜん', 'あいさつ'],
      correctAnswer: 0,
      explanation: '案内（あんない）意思是"引导、介绍"',
    },
    // 看假名选择汉字
    {
      id: 'n4-6',
      level: 'N4',
      type: 'hiragana-to-kanji',
      question: 'しばらく',
      options: ['暫く', '静か', '下', '時間'],
      correctAnswer: 0,
      explanation: 'しばらく（暫く）意思是"一会儿"',
    },
    {
      id: 'n4-7',
      level: 'N4',
      type: 'hiragana-to-kanji',
      question: 'ほんとう',
      options: ['本当', '本堂', '本番', '盆同'],
      correctAnswer: 0,
      explanation: 'ほんとう（本当）意思是"真的"',
    },
    {
      id: 'n4-8',
      level: 'N4',
      type: 'hiragana-to-kanji',
      question: 'かんたん',
      options: ['簡単', '歓談', '鑑定', '簡易'],
      correctAnswer: 0,
      explanation: 'かんたん（簡単）意思是"简单"',
    },
    {
      id: 'n4-9',
      level: 'N4',
      type: 'hiragana-to-kanji',
      question: 'けいかく',
      options: ['計画', '経験', '経済', '警察'],
      correctAnswer: 0,
      explanation: 'けいかく（計画）意思是"计划"',
    },
    {
      id: 'n4-10',
      level: 'N4',
      type: 'hiragana-to-kanji',
      question: 'しっぱい',
      options: ['失敗', '失礼', '辞典', '品物'],
      correctAnswer: 0,
      explanation: 'しっぱい（失敗）意思是"失败"',
    },
    // 片假名翻译成中文
    {
      id: 'n4-11',
      level: 'N4',
      type: 'katakana-to-chinese',
      question: 'アルコール',
      options: ['酒精', '亚洲', '非洲', '美国'],
      correctAnswer: 0,
      explanation: 'アルコール（alcohol）意思是"酒精"',
    },
    {
      id: 'n4-12',
      level: 'N4',
      type: 'katakana-to-chinese',
      question: 'アルバイト',
      options: ['兼职工作', '酒精', '亚洲', '非洲'],
      correctAnswer: 0,
      explanation: 'アルバイト（Arbeit）意思是"兼职工作"',
    },
    {
      id: 'n4-13',
      level: 'N4',
      type: 'katakana-to-chinese',
      question: 'スーパーマーケット',
      options: ['超市', '车站', '学校', '医院'],
      correctAnswer: 0,
      explanation: 'スーパーマーケット（supermarket）意思是"超市"',
    },
    {
      id: 'n4-14',
      level: 'N4',
      type: 'katakana-to-chinese',
      question: 'ステレオ',
      options: ['立体声音响', '头戴式耳机', '电脑', '手机链'],
      correctAnswer: 0,
      explanation: 'ステレオ（stereo）意思是"立体声音响"',
    },
    {
      id: 'n4-15',
      level: 'N4',
      type: 'katakana-to-chinese',
      question: 'プレゼント',
      options: ['礼物', '蛋糕', '面包', '咖啡'],
      correctAnswer: 0,
      explanation: 'プレゼント（present）意思是"礼物"',
    },
  ],
  N3: [
    // 看汉字选择平假名
    {
      id: 'n3-1',
      level: 'N3',
      type: 'kanji-to-hiragana',
      question: '港',
      options: ['みなと', 'ななみ', 'みなど', 'みねど'],
      correctAnswer: 0,
      explanation: '港（みなと）意思是"港口"',
    },
    {
      id: 'n3-2',
      level: 'N3',
      type: 'kanji-to-hiragana',
      question: '検討',
      options: ['けんとう', 'けんどう', 'けんさ', 'けんしょう'],
      correctAnswer: 0,
      explanation: '検討（けんとう）意思是"讨论、研究"',
    },
    {
      id: 'n3-3',
      level: 'N3',
      type: 'kanji-to-hiragana',
      question: '欠伸',
      options: ['あくび', 'けんしん', 'けんしょう', 'かんしん'],
      correctAnswer: 0,
      explanation: '欠伸（あくび）意思是"哈欠"',
    },
    {
      id: 'n3-4',
      level: 'N3',
      type: 'kanji-to-hiragana',
      question: '各々',
      options: ['おのおの', 'かくかく', 'かっかく', 'かくがく'],
      correctAnswer: 0,
      explanation: '各々（おのおの）意思是"各自"',
    },
    {
      id: 'n3-5',
      level: 'N3',
      type: 'kanji-to-hiragana',
      question: '淡い',
      options: ['あわい', 'あさい', 'たんい', 'えぐい'],
      correctAnswer: 0,
      explanation: '淡い（あわい）意思是"淡"',
    },
    // 新增N3单词
    {
      id: 'n3-16',
      level: 'N3',
      type: 'kanji-to-hiragana',
      question: '環境',
      options: ['かんきょう', 'がんけい', 'かんげい', 'かんこう'],
      correctAnswer: 0,
      explanation: '環境（かんきょう）意思是"环境"',
    },
    {
      id: 'n3-17',
      level: 'N3',
      type: 'kanji-to-hiragana',
      question: '教育',
      options: ['きょういく', 'こういく', 'きょうか', 'きょうき'],
      correctAnswer: 0,
      explanation: '教育（きょういく）意思是"教育"',
    },
    {
      id: 'n3-18',
      level: 'N3',
      type: 'kanji-to-hiragana',
      question: '経験',
      options: ['けいけん', 'けいげん', 'けいえん', 'けいき'],
      correctAnswer: 0,
      explanation: '経験（けいけん）意思是"经验"',
    },
    // 看假名选择汉字
    {
      id: 'n3-6',
      level: 'N3',
      type: 'hiragana-to-kanji',
      question: 'わらい',
      options: ['笑い', '筈井', '壊い', '肝煎'],
      correctAnswer: 0,
      explanation: 'わらい（笑い）意思是"笑"',
    },
    {
      id: 'n3-7',
      level: 'N3',
      type: 'hiragana-to-kanji',
      question: 'みずうみ',
      options: ['湖', '渓', '川', '河'],
      correctAnswer: 0,
      explanation: 'みずうみ（湖）意思是"湖"',
    },
    {
      id: 'n3-8',
      level: 'N3',
      type: 'hiragana-to-kanji',
      question: 'かみなり',
      options: ['雷', '吊り', '紡り', '神なり'],
      correctAnswer: 0,
      explanation: 'かみなり（雷）意思是"雷"',
    },
    {
      id: 'n3-9',
      level: 'N3',
      type: 'hiragana-to-kanji',
      question: 'ふり',
      options: ['振り', '摺り', '売り', '擦り'],
      correctAnswer: 0,
      explanation: 'ふり（振り）意思是"挥动、样子"',
    },
    {
      id: 'n3-10',
      level: 'N3',
      type: 'hiragana-to-kanji',
      question: 'つり',
      options: ['釣り', '連り', '張り', '罠り'],
      correctAnswer: 0,
      explanation: 'つり（釣り）意思是"钓鱼"',
    },
    // 新增N3假名转汉字
    {
      id: 'n3-19',
      level: 'N3',
      type: 'hiragana-to-kanji',
      question: 'けっこん',
      options: ['結婚', '結果', '結論', '結晶'],
      correctAnswer: 0,
      explanation: 'けっこん（結婚）意思是"结婚"',
    },
    {
      id: 'n3-20',
      level: 'N3',
      type: 'hiragana-to-kanji',
      question: 'はじめ',
      options: ['始め', '虐め', '恥じめ', '筈め'],
      correctAnswer: 0,
      explanation: 'はじめ（始め）意思是"开始"',
    },
    // 片假名翻译成中文
    {
      id: 'n3-11',
      level: 'N3',
      type: 'katakana-to-chinese',
      question: 'ライター',
      options: ['打火机', '编辑器', '信纸', '记者'],
      correctAnswer: 0,
      explanation: 'ライター（lighter）意思是"打火机"',
    },
    {
      id: 'n3-12',
      level: 'N3',
      type: 'katakana-to-chinese',
      question: 'ワクチン',
      options: ['疫苗', '脱产', '面包屑', '赌博'],
      correctAnswer: 0,
      explanation: 'ワクチン（vaccine）意思是"疫苗"',
    },
    {
      id: 'n3-13',
      level: 'N3',
      type: 'katakana-to-chinese',
      question: 'アクセサリー',
      options: ['装饰品', '建议', '想法', '酒精'],
      correctAnswer: 0,
      explanation: 'アクセサリー（accessory）意思是"装饰品"',
    },
    {
      id: 'n3-14',
      level: 'N3',
      type: 'katakana-to-chinese',
      question: 'イベント',
      options: ['活动', '印象', '形象', '采访'],
      correctAnswer: 0,
      explanation: 'イベント（event）意思是"活动"',
    },
    {
      id: 'n3-15',
      level: 'N3',
      type: 'katakana-to-chinese',
      question: 'イメージ',
      options: ['印象', '活动', '影像', '采访'],
      correctAnswer: 0,
      explanation: 'イメージ（image）意思是"印象、形象"',
    },
    // 新增N3片假名转中文
    {
      id: 'n3-21',
      level: 'N3',
      type: 'katakana-to-chinese',
      question: 'ペットボトル',
      options: ['塑料瓶', '宠物用喂食器', '奶瓶', '宠物盆'],
      correctAnswer: 0,
      explanation: 'ペットボトル（plastic bottle）意思是"塑料瓶"',
    },
    {
      id: 'n3-22',
      level: 'N3',
      type: 'katakana-to-chinese',
      question: 'バケツ',
      options: ['水桶', '篮球', '虫子', '球筐'],
      correctAnswer: 0,
      explanation: 'バケツ（bucket）意思是"水桶"',
    },
  ],
  N2: [
    // 看汉字选择平假名
    {
      id: 'n2-1',
      level: 'N2',
      type: 'kanji-to-hiragana',
      question: '蛇口',
      options: ['じゃぐち', 'じゃくち', 'しゃぐちゅ', 'しゃくち'],
      correctAnswer: 0,
      explanation: '蛇口（じゃぐち）意思是"水龙头"',
    },
    {
      id: 'n2-2',
      level: 'N2',
      type: 'kanji-to-hiragana',
      question: '献立',
      options: ['こんだて', 'けんだて', 'こんたて', 'けんたて'],
      correctAnswer: 0,
      explanation: '献立（こんだて）意思是"菜单"',
    },
    {
      id: 'n2-3',
      level: 'N2',
      type: 'kanji-to-hiragana',
      question: '争い',
      options: ['あらそい', 'あい', 'いきおい', 'たたかい'],
      correctAnswer: 0,
      explanation: '争い（あらそい）意思是"争论"',
    },
    {
      id: 'n2-4',
      level: 'N2',
      type: 'kanji-to-hiragana',
      question: '勢い',
      options: ['いきおい', 'あらそい', 'たたかい', 'ねらい'],
      correctAnswer: 0,
      explanation: '勢い（いきおい）意思是"气势"',
    },
    {
      id: 'n2-5',
      level: 'N2',
      type: 'kanji-to-hiragana',
      question: '戦い',
      options: ['たたかい', 'あらそい', 'いきおい', 'ねらい'],
      correctAnswer: 0,
      explanation: '戦い（たたかい）意思是"战斗"',
    },
    // 新增N2单词
    {
      id: 'n2-16',
      level: 'N2',
      type: 'kanji-to-hiragana',
      question: '強引',
      options: ['ごういん', 'きょういん', 'つよいい', 'けいいん'],
      correctAnswer: 0,
      explanation: '強引（ごういん）意思是"强制"',
    },
    {
      id: 'n2-17',
      level: 'N2',
      type: 'kanji-to-hiragana',
      question: '気障',
      options: ['きざ', 'きしょう', 'きざい', 'きざわり'],
      correctAnswer: 0,
      explanation: '気障（きざ）意思是"妆模作样，令人作呕"',
    },
    {
      id: 'n2-18',
      level: 'N2',
      type: 'kanji-to-hiragana',
      question: '図々しい',
      options: ['ずうずうしい', 'とどしい', 'ととしい', 'ずずしい'],
      correctAnswer: 0,
      explanation: '図々しい（ずうずうしい）意思是"厚颜无耻"',
    },
    // 看假名选择汉字
    {
      id: 'n2-6',
      level: 'N2',
      type: 'hiragana-to-kanji',
      question: 'たば',
      options: ['束', '弾', '支', '煙'],
      correctAnswer: 0,
      explanation: 'たば（束）意思是"把，捆"',
    },
    {
      id: 'n2-7',
      level: 'N2',
      type: 'hiragana-to-kanji',
      question: 'ほのお',
      options: ['炎', '帆', '火', '梶'],
      correctAnswer: 0,
      explanation: 'ほのお（炎）意思是"火焰，火苗"',
    },
    {
      id: 'n2-8',
      level: 'N2',
      type: 'hiragana-to-kanji',
      question: '厚かましい',
      options: ['あつかましい', 'あかましい', 'こまかしい', 'ふかましい'],
      correctAnswer: 0,
      explanation: '厚かましい（あつかましい）意思是"厚脸皮，无耻"',
    },
    {
      id: 'n2-9',
      level: 'N2',
      type: 'hiragana-to-kanji',
      question: 'よくばり',
      options: ['欲張り', '良く貼り', '翌貼り', '欲貼り'],
      correctAnswer: 0,
      explanation: 'よくばり（欲張り）意思是"含蓄，贪婪无厌"',
    },
    {
      id: 'n2-10',
      level: 'N2',
      type: 'hiragana-to-kanji',
      question: 'あずき',
      options: ['小豆', '預き', '赤木', '梓木'],
      correctAnswer: 0,
      explanation: 'あずき（小豆）意思是"红豆"',
    },
    // 新增N2假名转汉字
    {
      id: 'n2-19',
      level: 'N2',
      type: 'hiragana-to-kanji',
      question: 'のんき',
      options: ['吞気', '能気', '納機', '納期'],
      correctAnswer: 0,
      explanation: 'のんき（吞気）意思是"悠闲，不拘小节，不慌不忙"',
    },
    {
      id: 'n2-20',
      level: 'N2',
      type: 'hiragana-to-kanji',
      question: 'みじめ',
      options: ['惨め', '斜め', '始め', '虐め'],
      correctAnswer: 0,
      explanation: 'みじめ（惨め）意思是"凄惨，悲惨"',
    },
    // 片假名翻译成中文
    {
      id: 'n2-11',
      level: 'N2',
      type: 'katakana-to-chinese',
      question: 'コーラス',
      options: ['合唱', '呼吁', '混乱', '争执'],
      correctAnswer: 0,
      explanation: 'コーラス（chorus）意思是"合唱"',
    },
    {
      id: 'n2-12',
      level: 'N2',
      type: 'katakana-to-chinese',
      question: 'オルガン',
      options: ['风琴', '有机', '安装', '航空件'],
      correctAnswer: 0,
      explanation: 'オルガン（organ）意思是"风琴"',
    },
    {
      id: 'n2-13',
      level: 'N2',
      type: 'katakana-to-chinese',
      question: 'インストール',
      options: ['安装', '熨斗', '呼吁', '航空件'],
      correctAnswer: 0,
      explanation: 'インストール（install）意思是"安装"',
    },
    {
      id: 'n2-14',
      level: 'N2',
      type: 'katakana-to-chinese',
      question: 'ウール',
      options: ['羊毛', '意志', '面纱', '橡胶'],
      correctAnswer: 0,
      explanation: 'ウール（wool）意思是"羊毛"',
    },
    {
      id: 'n2-15',
      level: 'N2',
      type: 'katakana-to-chinese',
      question: 'コンクリート',
      options: ['水泥', '交流', '拐角', '橡胶'],
      correctAnswer: 0,
      explanation: 'コンクリート（concrete）意思是"水泥"',
    },
    // 新增N2片假名转中文
    {
      id: 'n2-21',
      level: 'N2',
      type: 'katakana-to-chinese',
      question: 'スチュワーデス',
      options: ['女服务员', '愚昧的人', '横插一脚的人', '老实人'],
      correctAnswer: 0,
      explanation: 'スチュワーデス（stewardess）意思是"女服务员"',
    },
    {
      id: 'n2-22',
      level: 'N2',
      type: 'katakana-to-chinese',
      question: 'ビニール',
      options: ['乙烯', '丙醇', '甲醇', '甲醛'],
      correctAnswer: 0,
      explanation: 'ビニール（vinyl）意思是"乙烯"',
    },
  ],
  N1: [
    // 看汉字选择平假名
    {
      id: 'n1-1',
      level: 'N1',
      type: 'kanji-to-hiragana',
      question: '厳か',
      options: ['おごそか', 'いそか', 'きびしか', 'げんか'],
      correctAnswer: 0,
      explanation: '厳か（おごそか）意思是"庄严肃穆"',
    },
    {
      id: 'n1-2',
      level: 'N1',
      type: 'kanji-to-hiragana',
      question: '恭しい',
      options: ['うやうやしい', 'きょうしい', 'れいぎただしい', 'ただしい'],
      correctAnswer: 0,
      explanation: '恭しい（うやうやしい）意思是"彬彬有礼"',
    },
    {
      id: 'n1-3',
      level: 'N1',
      type: 'kanji-to-hiragana',
      question: '扱い',
      options: ['あつかい', 'あつい', 'つい', 'きゅうい'],
      correctAnswer: 0,
      explanation: '扱い（あつかい）意思是"操作、对待"',
    },
    {
      id: 'n1-4',
      level: 'N1',
      type: 'kanji-to-hiragana',
      question: '麗らか',
      options: ['うららか', 'れいらか', 'きれいらか', 'うつくしらか'],
      correctAnswer: 0,
      explanation: '麗らか（うららか）意思是"和煦、晴朗"',
    },
    {
      id: 'n1-5',
      level: 'N1',
      type: 'kanji-to-hiragana',
      question: '取り扱い',
      options: ['とりあつかい', 'とりあいかい', 'とありつかい', 'とりかつあい'],
      correctAnswer: 0,
      explanation: '取り扱い（とりあつかい）意思是"使用、处理"',
    },
    // 新增N1单词
    {
      id: 'n1-16',
      level: 'N1',
      type: 'kanji-to-hiragana',
      question: '臆面',
      options: ['おくめん', 'おくげん', 'いめん', 'おけめん'],
      correctAnswer: 0,
      explanation: '臆面（おくめん）意思是"害羞、腼腆"',
    },
    {
      id: 'n1-17',
      level: 'N1',
      type: 'kanji-to-hiragana',
      question: '商う',
      options: ['あきなう', 'しょうう', 'あきう', 'かう'],
      correctAnswer: 0,
      explanation: '商う（あきなう）意思是"经营、买卖"',
    },
    {
      id: 'n1-18',
      level: 'N1',
      type: 'kanji-to-hiragana',
      question: '強ち',
      options: ['あながち', 'つよち', 'きょうち', 'よわち'],
      correctAnswer: 0,
      explanation: '強ち（あながち）意思是"未必"',
    },
    // 看假名选择汉字
    {
      id: 'n1-6',
      level: 'N1',
      type: 'hiragana-to-kanji',
      question: 'はて',
      options: ['果て', '涯て', '末て', '尽て'],
      correctAnswer: 0,
      explanation: 'はて（果て）意思是"尽头"',
    },
    {
      id: 'n1-7',
      level: 'N1',
      type: 'hiragana-to-kanji',
      question: 'つぐない',
      options: ['償い', '次ない', '継ぐない', '佃い'],
      correctAnswer: 0,
      explanation: 'つぐない（償い）意思是"补偿、赔偿"',
    },
    {
      id: 'n1-8',
      level: 'N1',
      type: 'hiragana-to-kanji',
      question: 'かすめる',
      options: ['掠める', '進める', '脱める', '破める'],
      correctAnswer: 0,
      explanation: '掠める（かすめる）意思是"掠夺、掠取；掠过、擦过"',
    },
    {
      id: 'n1-9',
      level: 'N1',
      type: 'hiragana-to-kanji',
      question: 'たんか',
      options: ['啖呵', '単語', '胆管', '嘆願'],
      correctAnswer: 0,
      explanation: 'たんか（啖呵）意思是"呵斥"',
    },
    {
      id: 'n1-10',
      level: 'N1',
      type: 'hiragana-to-kanji',
      question: 'ぐ',
      options: ['具', '区', '句', '苦'],
      correctAnswer: 0,
      explanation: 'ぐ（具）意思是"材料、工具"',
    },
    // 新增N1假名转汉字
    {
      id: 'n1-19',
      level: 'N1',
      type: 'hiragana-to-kanji',
      question: 'さいなむ',
      options: ['苛む', '刻む', '辱む', '跪む'],
      correctAnswer: 0,
      explanation: 'さいなむ（苛む）意思是"虐待、责备"',
    },
    {
      id: 'n1-20',
      level: 'N1',
      type: 'hiragana-to-kanji',
      question: 'こずえ',
      options: ['梢', '聆', '囀', '小豆'],
      correctAnswer: 0,
      explanation: 'こずえ（梢）意思是"树梢"',
    },
    // 片假名翻译成中文
    {
      id: 'n1-11',
      level: 'N1',
      type: 'katakana-to-chinese',
      question: 'アルカリ',
      options: ['碱、碱性', '卤', '铝合金', '钛'],
      correctAnswer: 0,
      explanation: 'アルカリ（alkali）意思是"碱、碱性"',
    },
    {
      id: 'n1-12',
      level: 'N1',
      type: 'katakana-to-chinese',
      question: 'インセンティブ',
      options: ['奖金', '访问', '布置', '取消'],
      correctAnswer: 0,
      explanation: 'インセンティブ（incentive）意思是"奖金"',
    },
    {
      id: 'n1-13',
      level: 'N1',
      type: 'katakana-to-chinese',
      question: 'アマチュア',
      options: ['业余爱好者', '老手', '高级玩家', '亚马逊'],
      correctAnswer: 0,
      explanation: 'アマチュア（amateur）意思是"业余爱好者"',
    },
    {
      id: 'n1-14',
      level: 'N1',
      type: 'katakana-to-chinese',
      question: 'ウイルス',
      options: ['病毒', '访问', '提高', '安排'],
      correctAnswer: 0,
      explanation: 'ウイルス（virus）意思是"病毒"',
    },
    {
      id: 'n1-15',
      level: 'N1',
      type: 'katakana-to-chinese',
      question: 'エピソード',
      options: ['插曲', '开放', '个性', '关键词'],
      correctAnswer: 0,
      explanation: 'エピソード（episode）意思是"插曲、逸事"',
    },
    // 新增N1片假名转中文
    {
      id: 'n1-21',
      level: 'N1',
      type: 'katakana-to-chinese',
      question: 'イノベーション',
      options: ['创新', '信息', '灵感', '印象'],
      correctAnswer: 0,
      explanation: 'イノベーション（innovation）意思是"创新"',
    },
    {
      id: 'n1-22',
      level: 'N1',
      type: 'katakana-to-chinese',
      question: 'シンポジウム',
      options: ['座谈会', '新加坡的', '标志性的', '研究的'],
      correctAnswer: 0,
      explanation: 'シンポジウム（symposium）意思是"座谈会"',
    },
  ],
}

// 自适应算法：根据答题情况决定下一题的难度
export function getNextQuestionLevel(
  currentLevel: JLPTLevel,
  recentAnswers: { isCorrect: boolean; level: JLPTLevel }[]
): JLPTLevel {
  const recentCount = recentAnswers.length
  if (recentCount < 3) return currentLevel

  const recentCorrect = recentAnswers.filter(a => a.isCorrect).length
  const correctRate = recentCorrect / recentCount

  const levelOrder: JLPTLevel[] = ['N5', 'N4', 'N3', 'N2', 'N1']
  const currentIndex = levelOrder.indexOf(currentLevel)

  if (correctRate >= 0.8 && currentIndex < levelOrder.length - 1) {
    // 正确率高，提升难度
    return levelOrder[currentIndex + 1]
  } else if (correctRate < 0.4 && currentIndex > 0) {
    // 正确率低，降低难度
    return levelOrder[currentIndex - 1]
  }

  return currentLevel
}

// 从指定级别随机选择一道题（不重复）
export function getRandomQuestion(level: JLPTLevel, usedQuestionIds: Set<string> = new Set()): Question | null {
  const questions = sampleQuestions[level]
  
  // 过滤出未使用的题目
  const availableQuestions = questions.filter(q => !usedQuestionIds.has(q.id))
  
  // 如果没有可用题目，返回null
  if (availableQuestions.length === 0) {
    return null
  }
  
  // 从可用题目中随机选择
  const randomIndex = Math.floor(Math.random() * availableQuestions.length)
  return availableQuestions[randomIndex]
}

// 获取指定级别的所有题目ID（用于检查是否还有可用题目）
export function getAllQuestionIds(level: JLPTLevel): string[] {
  return sampleQuestions[level].map(q => q.id)
}
