import { Question, JLPTLevel } from './types'

// 题目数据（根据参考网站整理）
export const sampleQuestions: Record<JLPTLevel, Question[]> = {
  N5: [
    // 看汉字选择平假名
    {
      id: 'n5-1',
      level: 'N5',
      type: 'kanji-to-hiragana',
      question: '影響',
      options: ['えいきょう', 'えいが', 'えいご', 'えん'],
      correctAnswer: 0,
      explanation: '影響（えいきょう）意思是"影响"',
    },
    {
      id: 'n5-2',
      level: 'N5',
      type: 'kanji-to-hiragana',
      question: '明るい',
      options: ['あかるい', 'あおい', 'あかい', 'あつい'],
      correctAnswer: 0,
      explanation: '明るい（あかるい）意思是"明亮的"',
    },
    {
      id: 'n5-3',
      level: 'N5',
      type: 'kanji-to-hiragana',
      question: '新しい',
      options: ['あたらしい', 'あつい', 'あまい', 'あさい'],
      correctAnswer: 0,
      explanation: '新しい（あたらしい）意思是"新的"',
    },
    {
      id: 'n5-4',
      level: 'N5',
      type: 'kanji-to-hiragana',
      question: '高い',
      options: ['たかい', 'たのしい', 'たべる', 'たまご'],
      correctAnswer: 0,
      explanation: '高い（たかい）意思是"高的"',
    },
    {
      id: 'n5-5',
      level: 'N5',
      type: 'kanji-to-hiragana',
      question: '大きい',
      options: ['おおきい', 'おいしい', 'おかあさん', 'おかね'],
      correctAnswer: 0,
      explanation: '大きい（おおきい）意思是"大的"',
    },
    // 看假名选择汉字
    {
      id: 'n5-6',
      level: 'N5',
      type: 'hiragana-to-kanji',
      question: 'あおい',
      options: ['青い', '赤い', '白い', '黒い'],
      correctAnswer: 0,
      explanation: 'あおい（青い）意思是"蓝色的"',
    },
    {
      id: 'n5-7',
      level: 'N5',
      type: 'hiragana-to-kanji',
      question: 'あさ',
      options: ['朝', '足', '頭', '手'],
      correctAnswer: 0,
      explanation: 'あさ（朝）意思是"早晨"',
    },
    {
      id: 'n5-8',
      level: 'N5',
      type: 'hiragana-to-kanji',
      question: 'いえ',
      options: ['家', '池', '椅子', '医者'],
      correctAnswer: 0,
      explanation: 'いえ（家）意思是"家"',
    },
    {
      id: 'n5-9',
      level: 'N5',
      type: 'hiragana-to-kanji',
      question: 'きのう',
      options: ['昨日', '今日', '明日', '今年'],
      correctAnswer: 0,
      explanation: 'きのう（昨日）意思是"昨天"',
    },
    {
      id: 'n5-10',
      level: 'N5',
      type: 'hiragana-to-kanji',
      question: 'こんにちは',
      options: ['今日は', '今週', '今月', '今年'],
      correctAnswer: 0,
      explanation: 'こんにちは（今日は）是问候语"你好"',
    },
    // 片假名翻译成中文
    {
      id: 'n5-11',
      level: 'N5',
      type: 'katakana-to-chinese',
      question: 'カメラ',
      options: ['照相机', '电脑', '电话', '电视'],
      correctAnswer: 0,
      explanation: 'カメラ（camera）意思是"照相机"',
    },
    {
      id: 'n5-12',
      level: 'N5',
      type: 'katakana-to-chinese',
      question: 'テレビ',
      options: ['电视', '电话', '桌子', '磁带'],
      correctAnswer: 0,
      explanation: 'テレビ（television）意思是"电视"',
    },
    {
      id: 'n5-13',
      level: 'N5',
      type: 'katakana-to-chinese',
      question: 'コーヒー',
      options: ['咖啡', '红茶', '绿茶', '果汁'],
      correctAnswer: 0,
      explanation: 'コーヒー（coffee）意思是"咖啡"',
    },
    {
      id: 'n5-14',
      level: 'N5',
      type: 'katakana-to-chinese',
      question: 'パン',
      options: ['面包', '米饭', '面条', '蛋糕'],
      correctAnswer: 0,
      explanation: 'パン（pan）意思是"面包"',
    },
    {
      id: 'n5-15',
      level: 'N5',
      type: 'katakana-to-chinese',
      question: 'ノート',
      options: ['笔记本', '铅笔', '橡皮', '书包'],
      correctAnswer: 0,
      explanation: 'ノート（note）意思是"笔记本"',
    },
  ],
  N4: [
    // 看汉字选择平假名
    {
      id: 'n4-1',
      level: 'N4',
      type: 'kanji-to-hiragana',
      question: '影響',
      options: ['えいきょう', 'えいが', 'えいご', 'えんりょ'],
      correctAnswer: 0,
      explanation: '影響（えいきょう）意思是"影响"',
    },
    {
      id: 'n4-2',
      level: 'N4',
      type: 'kanji-to-hiragana',
      question: '遠慮',
      options: ['えんりょ', 'えん', 'えいきょう', 'えいが'],
      correctAnswer: 0,
      explanation: '遠慮（えんりょ）意思是"客气"',
    },
    {
      id: 'n4-3',
      level: 'N4',
      type: 'kanji-to-hiragana',
      question: '安心',
      options: ['あんしん', 'あんぜん', 'あんない', 'あいさつ'],
      correctAnswer: 0,
      explanation: '安心（あんしん）意思是"安心"',
    },
    {
      id: 'n4-4',
      level: 'N4',
      type: 'kanji-to-hiragana',
      question: '安全',
      options: ['あんぜん', 'あんしん', 'あんない', 'あいさつ'],
      correctAnswer: 0,
      explanation: '安全（あんぜん）意思是"安全"',
    },
    {
      id: 'n4-5',
      level: 'N4',
      type: 'kanji-to-hiragana',
      question: '案内',
      options: ['あんない', 'あんしん', 'あんぜん', 'あいさつ'],
      correctAnswer: 0,
      explanation: '案内（あんない）意思是"引导、介绍"',
    },
    // 看假名选择汉字
    {
      id: 'n4-6',
      level: 'N4',
      type: 'hiragana-to-kanji',
      question: 'しばらく',
      options: ['暫く', '静か', '下', '時間'],
      correctAnswer: 0,
      explanation: 'しばらく（暫く）意思是"一会儿"',
    },
    {
      id: 'n4-7',
      level: 'N4',
      type: 'hiragana-to-kanji',
      question: 'きっと',
      options: ['必ず', '結構', '急', '急行'],
      correctAnswer: 0,
      explanation: 'きっと（必ず）意思是"一定"',
    },
    {
      id: 'n4-8',
      level: 'N4',
      type: 'hiragana-to-kanji',
      question: 'かんたん',
      options: ['簡単', '関係', '看護師', '頑張る'],
      correctAnswer: 0,
      explanation: 'かんたん（簡単）意思是"简单"',
    },
    {
      id: 'n4-9',
      level: 'N4',
      type: 'hiragana-to-kanji',
      question: 'けいかく',
      options: ['計画', '経験', '経済', '警察'],
      correctAnswer: 0,
      explanation: 'けいかく（計画）意思是"计划"',
    },
    {
      id: 'n4-10',
      level: 'N4',
      type: 'hiragana-to-kanji',
      question: 'しっぱい',
      options: ['失敗', '失礼', '辞典', '品物'],
      correctAnswer: 0,
      explanation: 'しっぱい（失敗）意思是"失败"',
    },
    // 片假名翻译成中文
    {
      id: 'n4-11',
      level: 'N4',
      type: 'katakana-to-chinese',
      question: 'アルコール',
      options: ['酒精', '亚洲', '非洲', '美国'],
      correctAnswer: 0,
      explanation: 'アルコール（alcohol）意思是"酒精"',
    },
    {
      id: 'n4-12',
      level: 'N4',
      type: 'katakana-to-chinese',
      question: 'アルバイト',
      options: ['兼职工作', '酒精', '亚洲', '非洲'],
      correctAnswer: 0,
      explanation: 'アルバイト（Arbeit）意思是"兼职工作"',
    },
    {
      id: 'n4-13',
      level: 'N4',
      type: 'katakana-to-chinese',
      question: 'スーパーマーケット',
      options: ['超市', '车站', '学校', '医院'],
      correctAnswer: 0,
      explanation: 'スーパーマーケット（supermarket）意思是"超市"',
    },
    {
      id: 'n4-14',
      level: 'N4',
      type: 'katakana-to-chinese',
      question: 'ステレオ',
      options: ['立体声音响', '电视', '电脑', '电话'],
      correctAnswer: 0,
      explanation: 'ステレオ（stereo）意思是"立体声音响"',
    },
    {
      id: 'n4-15',
      level: 'N4',
      type: 'katakana-to-chinese',
      question: 'プレゼント',
      options: ['礼物', '蛋糕', '面包', '咖啡'],
      correctAnswer: 0,
      explanation: 'プレゼント（present）意思是"礼物"',
    },
  ],
  N3: [
    // 看汉字选择平假名
    {
      id: 'n3-1',
      level: 'N3',
      type: 'kanji-to-hiragana',
      question: '影響',
      options: ['えいきょう', 'えいが', 'えいご', 'えんりょ'],
      correctAnswer: 0,
      explanation: '影響（えいきょう）意思是"影响"',
    },
    {
      id: 'n3-2',
      level: 'N3',
      type: 'kanji-to-hiragana',
      question: '検討',
      options: ['けんとう', 'けんきゅう', 'けんさ', 'けんしょう'],
      correctAnswer: 0,
      explanation: '検討（けんとう）意思是"讨论、研究"',
    },
    {
      id: 'n3-3',
      level: 'N3',
      type: 'kanji-to-hiragana',
      question: '互い',
      options: ['たがい', 'あい', 'おもい', 'かわり'],
      correctAnswer: 0,
      explanation: '互い（たがい）意思是"互相"',
    },
    {
      id: 'n3-4',
      level: 'N3',
      type: 'kanji-to-hiragana',
      question: '問い',
      options: ['とい', 'もん', 'しつもん', 'もんだい'],
      correctAnswer: 0,
      explanation: '問い（とい）意思是"提问"',
    },
    {
      id: 'n3-5',
      level: 'N3',
      type: 'kanji-to-hiragana',
      question: '祝い',
      options: ['いわい', 'しゅく', 'おいわい', 'しゅう'],
      correctAnswer: 0,
      explanation: '祝い（いわい）意思是"祝贺"',
    },
    // 看假名选择汉字
    {
      id: 'n3-6',
      level: 'N3',
      type: 'hiragana-to-kanji',
      question: 'わらい',
      options: ['笑い', '話', '花', '鼻'],
      correctAnswer: 0,
      explanation: 'わらい（笑い）意思是"笑"',
    },
    {
      id: 'n3-7',
      level: 'N3',
      type: 'hiragana-to-kanji',
      question: 'であい',
      options: ['出会い', '出発', '出かける', '出る'],
      correctAnswer: 0,
      explanation: 'であい（出会い）意思是"相遇"',
    },
    {
      id: 'n3-8',
      level: 'N3',
      type: 'hiragana-to-kanji',
      question: 'つくり',
      options: ['作り', '作る', '作', '作業'],
      correctAnswer: 0,
      explanation: 'つくり（作り）意思是"制作、构造"',
    },
    {
      id: 'n3-9',
      level: 'N3',
      type: 'hiragana-to-kanji',
      question: 'ふり',
      options: ['振り', '降り', '振る', '降る'],
      correctAnswer: 0,
      explanation: 'ふり（振り）意思是"挥动、样子"',
    },
    {
      id: 'n3-10',
      level: 'N3',
      type: 'hiragana-to-kanji',
      question: 'つり',
      options: ['釣り', '連れ', '連れる', '連'],
      correctAnswer: 0,
      explanation: 'つり（釣り）意思是"钓鱼"',
    },
    // 片假名翻译成中文
    {
      id: 'n3-11',
      level: 'N3',
      type: 'katakana-to-chinese',
      question: 'アイデア',
      options: ['想法', '建议', '装饰品', '酒精'],
      correctAnswer: 0,
      explanation: 'アイデア（idea）意思是"想法、主意"',
    },
    {
      id: 'n3-12',
      level: 'N3',
      type: 'katakana-to-chinese',
      question: 'アドバイス',
      options: ['建议', '想法', '装饰品', '酒精'],
      correctAnswer: 0,
      explanation: 'アドバイス（advice）意思是"建议"',
    },
    {
      id: 'n3-13',
      level: 'N3',
      type: 'katakana-to-chinese',
      question: 'アクセサリー',
      options: ['装饰品', '建议', '想法', '酒精'],
      correctAnswer: 0,
      explanation: 'アクセサリー（accessory）意思是"装饰品"',
    },
    {
      id: 'n3-14',
      level: 'N3',
      type: 'katakana-to-chinese',
      question: 'イベント',
      options: ['活动', '印象', '形象', '采访'],
      correctAnswer: 0,
      explanation: 'イベント（event）意思是"活动"',
    },
    {
      id: 'n3-15',
      level: 'N3',
      type: 'katakana-to-chinese',
      question: 'イメージ',
      options: ['印象', '活动', '形象', '采访'],
      correctAnswer: 0,
      explanation: 'イメージ（image）意思是"印象、形象"',
    },
  ],
  N2: [
    // 看汉字选择平假名
    {
      id: 'n2-1',
      level: 'N2',
      type: 'kanji-to-hiragana',
      question: '実施',
      options: ['じっし', 'じっけん', 'じつ', 'じっさい'],
      correctAnswer: 0,
      explanation: '実施（じっし）意思是"实施"',
    },
    {
      id: 'n2-2',
      level: 'N2',
      type: 'kanji-to-hiragana',
      question: '対応',
      options: ['たいおう', 'たい', 'たいりょう', 'たいせつ'],
      correctAnswer: 0,
      explanation: '対応（たいおう）意思是"对应"',
    },
    {
      id: 'n2-3',
      level: 'N2',
      type: 'kanji-to-hiragana',
      question: '争い',
      options: ['あらそい', 'あい', 'いきおい', 'たたかい'],
      correctAnswer: 0,
      explanation: '争い（あらそい）意思是"争论"',
    },
    {
      id: 'n2-4',
      level: 'N2',
      type: 'kanji-to-hiragana',
      question: '勢い',
      options: ['いきおい', 'あらそい', 'たたかい', 'ねらい'],
      correctAnswer: 0,
      explanation: '勢い（いきおい）意思是"气势"',
    },
    {
      id: 'n2-5',
      level: 'N2',
      type: 'kanji-to-hiragana',
      question: '戦い',
      options: ['たたかい', 'あらそい', 'いきおい', 'ねらい'],
      correctAnswer: 0,
      explanation: '戦い（たたかい）意思是"战斗"',
    },
    // 看假名选择汉字
    {
      id: 'n2-6',
      level: 'N2',
      type: 'hiragana-to-kanji',
      question: 'うたがい',
      options: ['疑い', '住まい', '支払い', '生きがい'],
      correctAnswer: 0,
      explanation: 'うたがい（疑い）意思是"怀疑"',
    },
    {
      id: 'n2-7',
      level: 'N2',
      type: 'hiragana-to-kanji',
      question: 'すまい',
      options: ['住まい', '疑い', '支払い', '生きがい'],
      correctAnswer: 0,
      explanation: 'すまい（住まい）意思是"住所"',
    },
    {
      id: 'n2-8',
      level: 'N2',
      type: 'hiragana-to-kanji',
      question: 'しはらい',
      options: ['支払い', '疑い', '住まい', '生きがい'],
      correctAnswer: 0,
      explanation: 'しはらい（支払い）意思是"支付"',
    },
    {
      id: 'n2-9',
      level: 'N2',
      type: 'hiragana-to-kanji',
      question: 'いきがい',
      options: ['生きがい', '疑い', '住まい', '支払い'],
      correctAnswer: 0,
      explanation: 'いきがい（生きがい）意思是"生存的意义"',
    },
    {
      id: 'n2-10',
      level: 'N2',
      type: 'hiragana-to-kanji',
      question: 'はなしあい',
      options: ['話し合い', '支払い', '住まい', '生きがい'],
      correctAnswer: 0,
      explanation: 'はなしあい（話し合い）意思是"商量"',
    },
    // 片假名翻译成中文
    {
      id: 'n2-11',
      level: 'N2',
      type: 'katakana-to-chinese',
      question: 'アイロン',
      options: ['熨斗', '呼吁', '安装', '航空件'],
      correctAnswer: 0,
      explanation: 'アイロン（iron）意思是"熨斗"',
    },
    {
      id: 'n2-12',
      level: 'N2',
      type: 'katakana-to-chinese',
      question: 'アピール',
      options: ['呼吁', '熨斗', '安装', '航空件'],
      correctAnswer: 0,
      explanation: 'アピール（appeal）意思是"呼吁"',
    },
    {
      id: 'n2-13',
      level: 'N2',
      type: 'katakana-to-chinese',
      question: 'インストール',
      options: ['安装', '熨斗', '呼吁', '航空件'],
      correctAnswer: 0,
      explanation: 'インストール（install）意思是"安装"',
    },
    {
      id: 'n2-14',
      level: 'N2',
      type: 'katakana-to-chinese',
      question: 'コミュニケーション',
      options: ['交流', '水泥', '拐角', '橡胶'],
      correctAnswer: 0,
      explanation: 'コミュニケーション（communication）意思是"交流"',
    },
    {
      id: 'n2-15',
      level: 'N2',
      type: 'katakana-to-chinese',
      question: 'コンクリート',
      options: ['水泥', '交流', '拐角', '橡胶'],
      correctAnswer: 0,
      explanation: 'コンクリート（concrete）意思是"水泥"',
    },
  ],
  N1: [
    // 看汉字选择平假名
    {
      id: 'n1-1',
      level: 'N1',
      type: 'kanji-to-hiragana',
      question: '現実的',
      options: ['げんじつてき', 'げんき', 'げんかん', 'げんいん'],
      correctAnswer: 0,
      explanation: '現実的（げんじつてき）意思是"现实的"',
    },
    {
      id: 'n1-2',
      level: 'N1',
      type: 'kanji-to-hiragana',
      question: '促進',
      options: ['そくしん', 'そく', 'そくてい', 'そくばく'],
      correctAnswer: 0,
      explanation: '促進（そくしん）意思是"促进"',
    },
    {
      id: 'n1-3',
      level: 'N1',
      type: 'kanji-to-hiragana',
      question: '扱い',
      options: ['あつかい', 'あつ', 'あつかう', 'あつめる'],
      correctAnswer: 0,
      explanation: '扱い（あつかい）意思是"操作、对待"',
    },
    {
      id: 'n1-4',
      level: 'N1',
      type: 'kanji-to-hiragana',
      question: '味わい',
      options: ['あじわい', 'あじ', 'み', 'あじわう'],
      correctAnswer: 0,
      explanation: '味わい（あじわい）意思是"味道、趣味"',
    },
    {
      id: 'n1-5',
      level: 'N1',
      type: 'kanji-to-hiragana',
      question: '取り扱い',
      options: ['とりあつかい', 'とり', 'あつかい', 'とる'],
      correctAnswer: 0,
      explanation: '取り扱い（とりあつかい）意思是"使用、处理"',
    },
    // 看假名选择汉字
    {
      id: 'n1-6',
      level: 'N1',
      type: 'hiragana-to-kanji',
      question: 'はて',
      options: ['果て', '果', '果物', '果実'],
      correctAnswer: 0,
      explanation: 'はて（果て）意思是"尽头"',
    },
    {
      id: 'n1-7',
      level: 'N1',
      type: 'hiragana-to-kanji',
      question: 'おもいやり',
      options: ['思いやり', '思い', '思う', '思考'],
      correctAnswer: 0,
      explanation: 'おもいやり（思いやり）意思是"体贴"',
    },
    {
      id: 'n1-8',
      level: 'N1',
      type: 'hiragana-to-kanji',
      question: 'よ',
      options: ['世', '夜', '四', '予'],
      correctAnswer: 0,
      explanation: 'よ（世）意思是"社会"',
    },
    {
      id: 'n1-9',
      level: 'N1',
      type: 'hiragana-to-kanji',
      question: 'とも',
      options: ['共', '友', '供', '供給'],
      correctAnswer: 0,
      explanation: 'とも（共）意思是"一起"',
    },
    {
      id: 'n1-10',
      level: 'N1',
      type: 'hiragana-to-kanji',
      question: 'ぐ',
      options: ['具', '具合', '具体', '道具'],
      correctAnswer: 0,
      explanation: 'ぐ（具）意思是"材料、工具"',
    },
    // 片假名翻译成中文
    {
      id: 'n1-11',
      level: 'N1',
      type: 'katakana-to-chinese',
      question: 'アクセス',
      options: ['访问', '提高', '布置', '病毒'],
      correctAnswer: 0,
      explanation: 'アクセス（access）意思是"访问、交通"',
    },
    {
      id: 'n1-12',
      level: 'N1',
      type: 'katakana-to-chinese',
      question: 'アップ',
      options: ['提高', '访问', '布置', '病毒'],
      correctAnswer: 0,
      explanation: 'アップ（up）意思是"提高"',
    },
    {
      id: 'n1-13',
      level: 'N1',
      type: 'katakana-to-chinese',
      question: 'アレンジ',
      options: ['安排', '访问', '提高', '病毒'],
      correctAnswer: 0,
      explanation: 'アレンジ（arrange）意思是"安排、布置"',
    },
    {
      id: 'n1-14',
      level: 'N1',
      type: 'katakana-to-chinese',
      question: 'ウイルス',
      options: ['病毒', '访问', '提高', '安排'],
      correctAnswer: 0,
      explanation: 'ウイルス（virus）意思是"病毒"',
    },
    {
      id: 'n1-15',
      level: 'N1',
      type: 'katakana-to-chinese',
      question: 'エピソード',
      options: ['插曲', '开放', '个性', '关键词'],
      correctAnswer: 0,
      explanation: 'エピソード（episode）意思是"插曲、逸事"',
    },
  ],
}

// 自适应算法：根据答题情况决定下一题的难度
export function getNextQuestionLevel(
  currentLevel: JLPTLevel,
  recentAnswers: { isCorrect: boolean; level: JLPTLevel }[]
): JLPTLevel {
  const recentCount = recentAnswers.length
  if (recentCount < 3) return currentLevel

  const recentCorrect = recentAnswers.filter(a => a.isCorrect).length
  const correctRate = recentCorrect / recentCount

  const levelOrder: JLPTLevel[] = ['N5', 'N4', 'N3', 'N2', 'N1']
  const currentIndex = levelOrder.indexOf(currentLevel)

  if (correctRate >= 0.8 && currentIndex < levelOrder.length - 1) {
    // 正确率高，提升难度
    return levelOrder[currentIndex + 1]
  } else if (correctRate < 0.4 && currentIndex > 0) {
    // 正确率低，降低难度
    return levelOrder[currentIndex - 1]
  }

  return currentLevel
}

// 从指定级别随机选择一道题（不重复）
export function getRandomQuestion(level: JLPTLevel, usedQuestionIds: Set<string> = new Set()): Question | null {
  const questions = sampleQuestions[level]
  
  // 过滤出未使用的题目
  const availableQuestions = questions.filter(q => !usedQuestionIds.has(q.id))
  
  // 如果没有可用题目，返回null
  if (availableQuestions.length === 0) {
    return null
  }
  
  // 从可用题目中随机选择
  const randomIndex = Math.floor(Math.random() * availableQuestions.length)
  return availableQuestions[randomIndex]
}

// 获取指定级别的所有题目ID（用于检查是否还有可用题目）
export function getAllQuestionIds(level: JLPTLevel): string[] {
  return sampleQuestions[level].map(q => q.id)
}
